package ebiNeutrinoSDK.model.hibernate;
// Generated 23-gen-2012 12.30.18 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Accountstack generated by hbm2java
 */
public class Accountstack  implements java.io.Serializable {


     private Integer acstackid;
     private String accountnr;
     private Integer accountType;
     private String accountTaxType;
     private String accountDebit;
     private String accountCredit;
     private String accountDName;
     private String accountCName;
     private Double accountCValue;
     private Double accountDValue;
     private String accountname;
     private Double accountvalue;
     private String description;
     private Date accountdate;
     private Date createddate;
     private String createdfrom;
     private String changedfrom;
     private Date changeddate;
     private Set<Accountstackdocs> accountstackdocses = new HashSet<Accountstackdocs>(0);

    public Accountstack() {
    }

    public Accountstack(String accountnr, Integer accountType, String accountTaxType, String accountDebit, String accountCredit, String accountDName, String accountCName, Double accountCValue, Double accountDValue, String accountname, Double accountvalue, String description, Date accountdate, Date createddate, String createdfrom, String changedfrom, Date changeddate, Set<Accountstackdocs> accountstackdocses) {
       this.accountnr = accountnr;
       this.accountType = accountType;
       this.accountTaxType = accountTaxType;
       this.accountDebit = accountDebit;
       this.accountCredit = accountCredit;
       this.accountDName = accountDName;
       this.accountCName = accountCName;
       this.accountCValue = accountCValue;
       this.accountDValue = accountDValue;
       this.accountname = accountname;
       this.accountvalue = accountvalue;
       this.description = description;
       this.accountdate = accountdate;
       this.createddate = createddate;
       this.createdfrom = createdfrom;
       this.changedfrom = changedfrom;
       this.changeddate = changeddate;
       this.accountstackdocses = accountstackdocses;
    }
   
    public Integer getAcstackid() {
        return this.acstackid;
    }
    
    public void setAcstackid(Integer acstackid) {
        this.acstackid = acstackid;
    }
    public String getAccountnr() {
        return this.accountnr;
    }
    
    public void setAccountnr(String accountnr) {
        this.accountnr = accountnr;
    }
    public Integer getAccountType() {
        return this.accountType;
    }
    
    public void setAccountType(Integer accountType) {
        this.accountType = accountType;
    }
    public String getAccountTaxType() {
        return this.accountTaxType;
    }
    
    public void setAccountTaxType(String accountTaxType) {
        this.accountTaxType = accountTaxType;
    }
    public String getAccountDebit() {
        return this.accountDebit;
    }
    
    public void setAccountDebit(String accountDebit) {
        this.accountDebit = accountDebit;
    }
    public String getAccountCredit() {
        return this.accountCredit;
    }
    
    public void setAccountCredit(String accountCredit) {
        this.accountCredit = accountCredit;
    }
    public String getAccountDName() {
        return this.accountDName;
    }
    
    public void setAccountDName(String accountDName) {
        this.accountDName = accountDName;
    }
    public String getAccountCName() {
        return this.accountCName;
    }
    
    public void setAccountCName(String accountCName) {
        this.accountCName = accountCName;
    }
    public Double getAccountCValue() {
        return this.accountCValue;
    }
    
    public void setAccountCValue(Double accountCValue) {
        this.accountCValue = accountCValue;
    }
    public Double getAccountDValue() {
        return this.accountDValue;
    }
    
    public void setAccountDValue(Double accountDValue) {
        this.accountDValue = accountDValue;
    }
    public String getAccountname() {
        return this.accountname;
    }
    
    public void setAccountname(String accountname) {
        this.accountname = accountname;
    }
    public Double getAccountvalue() {
        return this.accountvalue;
    }
    
    public void setAccountvalue(Double accountvalue) {
        this.accountvalue = accountvalue;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getAccountdate() {
        return this.accountdate;
    }
    
    public void setAccountdate(Date accountdate) {
        this.accountdate = accountdate;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getCreatedfrom() {
        return this.createdfrom;
    }
    
    public void setCreatedfrom(String createdfrom) {
        this.createdfrom = createdfrom;
    }
    public String getChangedfrom() {
        return this.changedfrom;
    }
    
    public void setChangedfrom(String changedfrom) {
        this.changedfrom = changedfrom;
    }
    public Date getChangeddate() {
        return this.changeddate;
    }
    
    public void setChangeddate(Date changeddate) {
        this.changeddate = changeddate;
    }
    public Set<Accountstackdocs> getAccountstackdocses() {
        return this.accountstackdocses;
    }
    
    public void setAccountstackdocses(Set<Accountstackdocs> accountstackdocses) {
        this.accountstackdocses = accountstackdocses;
    }




}


