package ebiNeutrinoSDK.model.hibernate;
// Generated 23-gen-2012 12.30.18 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Accountstackdocs generated by hbm2java
 */
public class Accountstackdocs  implements java.io.Serializable {


     private Integer accountdocid;
     private Accountstack accountstack;
     private String name;
     private byte[] files;
     private Date createddate;
     private String createdfrom;

    public Accountstackdocs() {
    }

    public Accountstackdocs(Accountstack accountstack, String name, byte[] files, Date createddate, String createdfrom) {
       this.accountstack = accountstack;
       this.name = name;
       this.files = files;
       this.createddate = createddate;
       this.createdfrom = createdfrom;
    }
   
    public Integer getAccountdocid() {
        return this.accountdocid;
    }
    
    public void setAccountdocid(Integer accountdocid) {
        this.accountdocid = accountdocid;
    }
    public Accountstack getAccountstack() {
        return this.accountstack;
    }
    
    public void setAccountstack(Accountstack accountstack) {
        this.accountstack = accountstack;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public byte[] getFiles() {
        return this.files;
    }
    
    public void setFiles(byte[] files) {
        this.files = files;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getCreatedfrom() {
        return this.createdfrom;
    }
    
    public void setCreatedfrom(String createdfrom) {
        this.createdfrom = createdfrom;
    }




}


