package ebiNeutrinoSDK.model.hibernate;
// Generated 23-gen-2012 12.30.18 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Accountstackcd generated by hbm2java
 */
public class Accountstackcd  implements java.io.Serializable {


     private Integer accountstackcdid;
     private Integer accountstackid;
     private String creditdebitnumber;
     private String creditdebitname;
     private Double creditdebitvalue;
     private String creditdebittaxtname;
     private Integer creditdebittype;
     private String createdfrom;
     private Date createddate;

    public Accountstackcd() {
    }

    public Accountstackcd(Integer accountstackid, String creditdebitnumber, String creditdebitname, Double creditdebitvalue, String creditdebittaxtname, Integer creditdebittype, String createdfrom, Date createddate) {
       this.accountstackid = accountstackid;
       this.creditdebitnumber = creditdebitnumber;
       this.creditdebitname = creditdebitname;
       this.creditdebitvalue = creditdebitvalue;
       this.creditdebittaxtname = creditdebittaxtname;
       this.creditdebittype = creditdebittype;
       this.createdfrom = createdfrom;
       this.createddate = createddate;
    }
   
    public Integer getAccountstackcdid() {
        return this.accountstackcdid;
    }
    
    public void setAccountstackcdid(Integer accountstackcdid) {
        this.accountstackcdid = accountstackcdid;
    }
    public Integer getAccountstackid() {
        return this.accountstackid;
    }
    
    public void setAccountstackid(Integer accountstackid) {
        this.accountstackid = accountstackid;
    }
    public String getCreditdebitnumber() {
        return this.creditdebitnumber;
    }
    
    public void setCreditdebitnumber(String creditdebitnumber) {
        this.creditdebitnumber = creditdebitnumber;
    }
    public String getCreditdebitname() {
        return this.creditdebitname;
    }
    
    public void setCreditdebitname(String creditdebitname) {
        this.creditdebitname = creditdebitname;
    }
    public Double getCreditdebitvalue() {
        return this.creditdebitvalue;
    }
    
    public void setCreditdebitvalue(Double creditdebitvalue) {
        this.creditdebitvalue = creditdebitvalue;
    }
    public String getCreditdebittaxtname() {
        return this.creditdebittaxtname;
    }
    
    public void setCreditdebittaxtname(String creditdebittaxtname) {
        this.creditdebittaxtname = creditdebittaxtname;
    }
    public Integer getCreditdebittype() {
        return this.creditdebittype;
    }
    
    public void setCreditdebittype(Integer creditdebittype) {
        this.creditdebittype = creditdebittype;
    }
    public String getCreatedfrom() {
        return this.createdfrom;
    }
    
    public void setCreatedfrom(String createdfrom) {
        this.createdfrom = createdfrom;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }




}


