package ebiNeutrinoSDK.model.hibernate;
// Generated 23-gen-2012 12.30.18 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Companyactivitiesdocs generated by hbm2java
 */
public class Companyactivitiesdocs  implements java.io.Serializable {


     private Integer activitydocid;
     private Companyactivities companyactivities;
     private String name;
     private byte[] files;
     private Date createddate;
     private String createdfrom;

    public Companyactivitiesdocs() {
    }

    public Companyactivitiesdocs(Companyactivities companyactivities, String name, byte[] files, Date createddate, String createdfrom) {
       this.companyactivities = companyactivities;
       this.name = name;
       this.files = files;
       this.createddate = createddate;
       this.createdfrom = createdfrom;
    }
   
    public Integer getActivitydocid() {
        return this.activitydocid;
    }
    
    public void setActivitydocid(Integer activitydocid) {
        this.activitydocid = activitydocid;
    }
    public Companyactivities getCompanyactivities() {
        return this.companyactivities;
    }
    
    public void setCompanyactivities(Companyactivities companyactivities) {
        this.companyactivities = companyactivities;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public byte[] getFiles() {
        return this.files;
    }
    
    public void setFiles(byte[] files) {
        this.files = files;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getCreatedfrom() {
        return this.createdfrom;
    }
    
    public void setCreatedfrom(String createdfrom) {
        this.createdfrom = createdfrom;
    }




}


