package ebiNeutrinoSDK.model.hibernate;
// Generated 23-gen-2012 12.30.18 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Companyproducttax generated by hbm2java
 */
public class Companyproducttax  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Double taxvalue;
     private Date createddate;
     private String createdfrom;
     private Date changeddate;
     private String changedfrom;

    public Companyproducttax() {
    }

    public Companyproducttax(String name, Double taxvalue, Date createddate, String createdfrom, Date changeddate, String changedfrom) {
       this.name = name;
       this.taxvalue = taxvalue;
       this.createddate = createddate;
       this.createdfrom = createdfrom;
       this.changeddate = changeddate;
       this.changedfrom = changedfrom;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Double getTaxvalue() {
        return this.taxvalue;
    }
    
    public void setTaxvalue(Double taxvalue) {
        this.taxvalue = taxvalue;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getCreatedfrom() {
        return this.createdfrom;
    }
    
    public void setCreatedfrom(String createdfrom) {
        this.createdfrom = createdfrom;
    }
    public Date getChangeddate() {
        return this.changeddate;
    }
    
    public void setChangeddate(Date changeddate) {
        this.changeddate = changeddate;
    }
    public String getChangedfrom() {
        return this.changedfrom;
    }
    
    public void setChangedfrom(String changedfrom) {
        this.changedfrom = changedfrom;
    }




}


