package ebiNeutrinoSDK.model.hibernate;
// Generated 23-gen-2012 12.30.18 by Hibernate Tools 3.4.0.CR1



/**
 * Companynumber generated by hbm2java
 */
public class Companynumber  implements java.io.Serializable {


     private Integer id;
     private Companycategory companycategory;
     private String category;
     private String beginchar;
     private Integer numberfrom;
     private Integer numberto;

    public Companynumber() {
    }

    public Companynumber(Companycategory companycategory, String category, String beginchar, Integer numberfrom, Integer numberto) {
       this.companycategory = companycategory;
       this.category = category;
       this.beginchar = beginchar;
       this.numberfrom = numberfrom;
       this.numberto = numberto;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Companycategory getCompanycategory() {
        return this.companycategory;
    }
    
    public void setCompanycategory(Companycategory companycategory) {
        this.companycategory = companycategory;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public String getBeginchar() {
        return this.beginchar;
    }
    
    public void setBeginchar(String beginchar) {
        this.beginchar = beginchar;
    }
    public Integer getNumberfrom() {
        return this.numberfrom;
    }
    
    public void setNumberfrom(Integer numberfrom) {
        this.numberfrom = numberfrom;
    }
    public Integer getNumberto() {
        return this.numberto;
    }
    
    public void setNumberto(Integer numberto) {
        this.numberto = numberto;
    }




}


