package ebiNeutrinoSDK.model.hibernate;
// Generated 23-gen-2012 12.30.18 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Companymeetingdoc generated by hbm2java
 */
public class Companymeetingdoc  implements java.io.Serializable {


     private Integer meetingdocid;
     private Companymeetingprotocol companymeetingprotocol;
     private String name;
     private byte[] files;
     private Date createddate;
     private String createdfrom;

    public Companymeetingdoc() {
    }

    public Companymeetingdoc(Companymeetingprotocol companymeetingprotocol, String name, byte[] files, Date createddate, String createdfrom) {
       this.companymeetingprotocol = companymeetingprotocol;
       this.name = name;
       this.files = files;
       this.createddate = createddate;
       this.createdfrom = createdfrom;
    }
   
    public Integer getMeetingdocid() {
        return this.meetingdocid;
    }
    
    public void setMeetingdocid(Integer meetingdocid) {
        this.meetingdocid = meetingdocid;
    }
    public Companymeetingprotocol getCompanymeetingprotocol() {
        return this.companymeetingprotocol;
    }
    
    public void setCompanymeetingprotocol(Companymeetingprotocol companymeetingprotocol) {
        this.companymeetingprotocol = companymeetingprotocol;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public byte[] getFiles() {
        return this.files;
    }
    
    public void setFiles(byte[] files) {
        this.files = files;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getCreatedfrom() {
        return this.createdfrom;
    }
    
    public void setCreatedfrom(String createdfrom) {
        this.createdfrom = createdfrom;
    }




}


