package ebiNeutrinoSDK.model.hibernate;
// Generated 23-gen-2012 12.30.18 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Companyorderdocs generated by hbm2java
 */
public class Companyorderdocs  implements java.io.Serializable {


     private Integer orderdocid;
     private Companyorder companyorder;
     private String name;
     private byte[] files;
     private String createdfrom;
     private Date createddate;

    public Companyorderdocs() {
    }

    public Companyorderdocs(Companyorder companyorder, String name, byte[] files, String createdfrom, Date createddate) {
       this.companyorder = companyorder;
       this.name = name;
       this.files = files;
       this.createdfrom = createdfrom;
       this.createddate = createddate;
    }
   
    public Integer getOrderdocid() {
        return this.orderdocid;
    }
    
    public void setOrderdocid(Integer orderdocid) {
        this.orderdocid = orderdocid;
    }
    public Companyorder getCompanyorder() {
        return this.companyorder;
    }
    
    public void setCompanyorder(Companyorder companyorder) {
        this.companyorder = companyorder;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public byte[] getFiles() {
        return this.files;
    }
    
    public void setFiles(byte[] files) {
        this.files = files;
    }
    public String getCreatedfrom() {
        return this.createdfrom;
    }
    
    public void setCreatedfrom(String createdfrom) {
        this.createdfrom = createdfrom;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }




}


