package ebiNeutrinoSDK.model.hibernate;
// Generated 23-gen-2012 12.30.18 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Companyorder generated by hbm2java
 */
public class Companyorder  implements java.io.Serializable {


     private Integer orderid;
     private Company company;
     private String ordernr;
     private Integer offerid;
     private String name;
     private Boolean invoicecreated;
     private String status;
     private Integer orderversion;
     private Date offerdate;
     private Date validto;
     private Boolean isrecieved;
     private String description;
     private String createdfrom;
     private Date createddate;
     private String changedfrom;
     private Date changeddate;
     private Set<Companyorderdocs> companyorderdocses = new HashSet<Companyorderdocs>(0);
     private Set<Companyorderpositions> companyorderpositionses = new HashSet<Companyorderpositions>(0);
     private Set<Companyorderreceiver> companyorderreceivers = new HashSet<Companyorderreceiver>(0);

    public Companyorder() {
    }

    public Companyorder(Company company, String ordernr, Integer offerid, String name, Boolean invoicecreated, String status, Integer orderversion, Date offerdate, Date validto, Boolean isrecieved, String description, String createdfrom, Date createddate, String changedfrom, Date changeddate, Set<Companyorderdocs> companyorderdocses, Set<Companyorderpositions> companyorderpositionses, Set<Companyorderreceiver> companyorderreceivers) {
       this.company = company;
       this.ordernr = ordernr;
       this.offerid = offerid;
       this.name = name;
       this.invoicecreated = invoicecreated;
       this.status = status;
       this.orderversion = orderversion;
       this.offerdate = offerdate;
       this.validto = validto;
       this.isrecieved = isrecieved;
       this.description = description;
       this.createdfrom = createdfrom;
       this.createddate = createddate;
       this.changedfrom = changedfrom;
       this.changeddate = changeddate;
       this.companyorderdocses = companyorderdocses;
       this.companyorderpositionses = companyorderpositionses;
       this.companyorderreceivers = companyorderreceivers;
    }
   
    public Integer getOrderid() {
        return this.orderid;
    }
    
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    public String getOrdernr() {
        return this.ordernr;
    }
    
    public void setOrdernr(String ordernr) {
        this.ordernr = ordernr;
    }
    public Integer getOfferid() {
        return this.offerid;
    }
    
    public void setOfferid(Integer offerid) {
        this.offerid = offerid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Boolean getInvoicecreated() {
        return this.invoicecreated;
    }
    
    public void setInvoicecreated(Boolean invoicecreated) {
        this.invoicecreated = invoicecreated;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Integer getOrderversion() {
        return this.orderversion;
    }
    
    public void setOrderversion(Integer orderversion) {
        this.orderversion = orderversion;
    }
    public Date getOfferdate() {
        return this.offerdate;
    }
    
    public void setOfferdate(Date offerdate) {
        this.offerdate = offerdate;
    }
    public Date getValidto() {
        return this.validto;
    }
    
    public void setValidto(Date validto) {
        this.validto = validto;
    }
    public Boolean getIsrecieved() {
        return this.isrecieved;
    }
    
    public void setIsrecieved(Boolean isrecieved) {
        this.isrecieved = isrecieved;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getCreatedfrom() {
        return this.createdfrom;
    }
    
    public void setCreatedfrom(String createdfrom) {
        this.createdfrom = createdfrom;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getChangedfrom() {
        return this.changedfrom;
    }
    
    public void setChangedfrom(String changedfrom) {
        this.changedfrom = changedfrom;
    }
    public Date getChangeddate() {
        return this.changeddate;
    }
    
    public void setChangeddate(Date changeddate) {
        this.changeddate = changeddate;
    }
    public Set<Companyorderdocs> getCompanyorderdocses() {
        return this.companyorderdocses;
    }
    
    public void setCompanyorderdocses(Set<Companyorderdocs> companyorderdocses) {
        this.companyorderdocses = companyorderdocses;
    }
    public Set<Companyorderpositions> getCompanyorderpositionses() {
        return this.companyorderpositionses;
    }
    
    public void setCompanyorderpositionses(Set<Companyorderpositions> companyorderpositionses) {
        this.companyorderpositionses = companyorderpositionses;
    }
    public Set<Companyorderreceiver> getCompanyorderreceivers() {
        return this.companyorderreceivers;
    }
    
    public void setCompanyorderreceivers(Set<Companyorderreceiver> companyorderreceivers) {
        this.companyorderreceivers = companyorderreceivers;
    }




}


