package ebiNeutrinoSDK.model.hibernate;
// Generated 23-gen-2012 12.30.18 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Companybank generated by hbm2java
 */
public class Companybank  implements java.io.Serializable {


     private Integer bankid;
     private Company company;
     private String bankname;
     private String bankbsb;
     private String bankaccount;
     private String bankbic;
     private String bankiban;
     private String bankcountry;
     private String createdfrom;
     private Date createddate;
     private String changedfrom;
     private Date changeddate;

    public Companybank() {
    }

    public Companybank(Company company, String bankname, String bankbsb, String bankaccount, String bankbic, String bankiban, String bankcountry, String createdfrom, Date createddate, String changedfrom, Date changeddate) {
       this.company = company;
       this.bankname = bankname;
       this.bankbsb = bankbsb;
       this.bankaccount = bankaccount;
       this.bankbic = bankbic;
       this.bankiban = bankiban;
       this.bankcountry = bankcountry;
       this.createdfrom = createdfrom;
       this.createddate = createddate;
       this.changedfrom = changedfrom;
       this.changeddate = changeddate;
    }
   
    public Integer getBankid() {
        return this.bankid;
    }
    
    public void setBankid(Integer bankid) {
        this.bankid = bankid;
    }
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    public String getBankname() {
        return this.bankname;
    }
    
    public void setBankname(String bankname) {
        this.bankname = bankname;
    }
    public String getBankbsb() {
        return this.bankbsb;
    }
    
    public void setBankbsb(String bankbsb) {
        this.bankbsb = bankbsb;
    }
    public String getBankaccount() {
        return this.bankaccount;
    }
    
    public void setBankaccount(String bankaccount) {
        this.bankaccount = bankaccount;
    }
    public String getBankbic() {
        return this.bankbic;
    }
    
    public void setBankbic(String bankbic) {
        this.bankbic = bankbic;
    }
    public String getBankiban() {
        return this.bankiban;
    }
    
    public void setBankiban(String bankiban) {
        this.bankiban = bankiban;
    }
    public String getBankcountry() {
        return this.bankcountry;
    }
    
    public void setBankcountry(String bankcountry) {
        this.bankcountry = bankcountry;
    }
    public String getCreatedfrom() {
        return this.createdfrom;
    }
    
    public void setCreatedfrom(String createdfrom) {
        this.createdfrom = createdfrom;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getChangedfrom() {
        return this.changedfrom;
    }
    
    public void setChangedfrom(String changedfrom) {
        this.changedfrom = changedfrom;
    }
    public Date getChangeddate() {
        return this.changeddate;
    }
    
    public void setChangeddate(Date changeddate) {
        this.changeddate = changeddate;
    }




}


