package ebiNeutrinoSDK.model.hibernate;
// Generated 23-gen-2012 12.30.18 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Companyactivities generated by hbm2java
 */
public class Companyactivities  implements java.io.Serializable {


     private Integer activityid;
     private Company company;
     private String activityname;
     private String activitytype;
     private String activitystatus;
     private Date duedate;
     private Integer duration;
     private String acolor;
     private Date activityclosedate;
     private Boolean activityisclosed;
     private String activitydescription;
     private Boolean islock;
     private String createdfrom;
     private Date createddate;
     private String changedfrom;
     private Date changeddate;
     private Integer timerstart;
     private Integer timerdisabled;
     private String timerExtra;
     private Set<Companyactivitiesdocs> companyactivitiesdocses = new HashSet<Companyactivitiesdocs>(0);

    public Companyactivities() {
    }

    public Companyactivities(Company company, String activityname, String activitytype, String activitystatus, Date duedate, Integer duration, String acolor, Date activityclosedate, Boolean activityisclosed, String activitydescription, Boolean islock, String createdfrom, Date createddate, String changedfrom, Date changeddate, Integer timerstart, Integer timerdisabled, String timerExtra, Set<Companyactivitiesdocs> companyactivitiesdocses) {
       this.company = company;
       this.activityname = activityname;
       this.activitytype = activitytype;
       this.activitystatus = activitystatus;
       this.duedate = duedate;
       this.duration = duration;
       this.acolor = acolor;
       this.activityclosedate = activityclosedate;
       this.activityisclosed = activityisclosed;
       this.activitydescription = activitydescription;
       this.islock = islock;
       this.createdfrom = createdfrom;
       this.createddate = createddate;
       this.changedfrom = changedfrom;
       this.changeddate = changeddate;
       this.timerstart = timerstart;
       this.timerdisabled = timerdisabled;
       this.timerExtra = timerExtra;
       this.companyactivitiesdocses = companyactivitiesdocses;
    }
   
    public Integer getActivityid() {
        return this.activityid;
    }
    
    public void setActivityid(Integer activityid) {
        this.activityid = activityid;
    }
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    public String getActivityname() {
        return this.activityname;
    }
    
    public void setActivityname(String activityname) {
        this.activityname = activityname;
    }
    public String getActivitytype() {
        return this.activitytype;
    }
    
    public void setActivitytype(String activitytype) {
        this.activitytype = activitytype;
    }
    public String getActivitystatus() {
        return this.activitystatus;
    }
    
    public void setActivitystatus(String activitystatus) {
        this.activitystatus = activitystatus;
    }
    public Date getDuedate() {
        return this.duedate;
    }
    
    public void setDuedate(Date duedate) {
        this.duedate = duedate;
    }
    public Integer getDuration() {
        return this.duration;
    }
    
    public void setDuration(Integer duration) {
        this.duration = duration;
    }
    public String getAcolor() {
        return this.acolor;
    }
    
    public void setAcolor(String acolor) {
        this.acolor = acolor;
    }
    public Date getActivityclosedate() {
        return this.activityclosedate;
    }
    
    public void setActivityclosedate(Date activityclosedate) {
        this.activityclosedate = activityclosedate;
    }
    public Boolean getActivityisclosed() {
        return this.activityisclosed;
    }
    
    public void setActivityisclosed(Boolean activityisclosed) {
        this.activityisclosed = activityisclosed;
    }
    public String getActivitydescription() {
        return this.activitydescription;
    }
    
    public void setActivitydescription(String activitydescription) {
        this.activitydescription = activitydescription;
    }
    public Boolean getIslock() {
        return this.islock;
    }
    
    public void setIslock(Boolean islock) {
        this.islock = islock;
    }
    public String getCreatedfrom() {
        return this.createdfrom;
    }
    
    public void setCreatedfrom(String createdfrom) {
        this.createdfrom = createdfrom;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getChangedfrom() {
        return this.changedfrom;
    }
    
    public void setChangedfrom(String changedfrom) {
        this.changedfrom = changedfrom;
    }
    public Date getChangeddate() {
        return this.changeddate;
    }
    
    public void setChangeddate(Date changeddate) {
        this.changeddate = changeddate;
    }
    public Integer getTimerstart() {
        return this.timerstart;
    }
    
    public void setTimerstart(Integer timerstart) {
        this.timerstart = timerstart;
    }
    public Integer getTimerdisabled() {
        return this.timerdisabled;
    }
    
    public void setTimerdisabled(Integer timerdisabled) {
        this.timerdisabled = timerdisabled;
    }
    public String getTimerExtra() {
        return this.timerExtra;
    }
    
    public void setTimerExtra(String timerExtra) {
        this.timerExtra = timerExtra;
    }
    public Set<Companyactivitiesdocs> getCompanyactivitiesdocses() {
        return this.companyactivitiesdocses;
    }
    
    public void setCompanyactivitiesdocses(Set<Companyactivitiesdocs> companyactivitiesdocses) {
        this.companyactivitiesdocses = companyactivitiesdocses;
    }




}


