package ebiNeutrinoSDK.model.hibernate;
// Generated 23-gen-2012 12.30.18 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Companyhirarchie generated by hbm2java
 */
public class Companyhirarchie  implements java.io.Serializable {


     private Integer hierarchieid;
     private Company company;
     private String name;
     private Integer root;
     private Integer parent;
     private String createdfrom;
     private Date createddate;
     private String changedfrom;
     private Date changeddate;

    public Companyhirarchie() {
    }

    public Companyhirarchie(Company company, String name, Integer root, Integer parent, String createdfrom, Date createddate, String changedfrom, Date changeddate) {
       this.company = company;
       this.name = name;
       this.root = root;
       this.parent = parent;
       this.createdfrom = createdfrom;
       this.createddate = createddate;
       this.changedfrom = changedfrom;
       this.changeddate = changeddate;
    }
   
    public Integer getHierarchieid() {
        return this.hierarchieid;
    }
    
    public void setHierarchieid(Integer hierarchieid) {
        this.hierarchieid = hierarchieid;
    }
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getRoot() {
        return this.root;
    }
    
    public void setRoot(Integer root) {
        this.root = root;
    }
    public Integer getParent() {
        return this.parent;
    }
    
    public void setParent(Integer parent) {
        this.parent = parent;
    }
    public String getCreatedfrom() {
        return this.createdfrom;
    }
    
    public void setCreatedfrom(String createdfrom) {
        this.createdfrom = createdfrom;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getChangedfrom() {
        return this.changedfrom;
    }
    
    public void setChangedfrom(String changedfrom) {
        this.changedfrom = changedfrom;
    }
    public Date getChangeddate() {
        return this.changeddate;
    }
    
    public void setChangeddate(Date changeddate) {
        this.changeddate = changeddate;
    }




}


