package ebiNeutrinoSDK.model.hibernate;
// Generated 23-gen-2012 12.30.18 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Companymeetingprotocol generated by hbm2java
 */
public class Companymeetingprotocol  implements java.io.Serializable {


     private Integer meetingprotocolid;
     private Company company;
     private String meetingsubject;
     private String meetingtype;
     private String protocol;
     private Date metingdate;
     private String createdfrom;
     private Date createddate;
     private String changedfrom;
     private Date changeddate;
     private Set<Companymeetingdoc> companymeetingdocs = new HashSet<Companymeetingdoc>(0);
     private Set<Companymeetingcontacts> companymeetingcontactses = new HashSet<Companymeetingcontacts>(0);

    public Companymeetingprotocol() {
    }

    public Companymeetingprotocol(Company company, String meetingsubject, String meetingtype, String protocol, Date metingdate, String createdfrom, Date createddate, String changedfrom, Date changeddate, Set<Companymeetingdoc> companymeetingdocs, Set<Companymeetingcontacts> companymeetingcontactses) {
       this.company = company;
       this.meetingsubject = meetingsubject;
       this.meetingtype = meetingtype;
       this.protocol = protocol;
       this.metingdate = metingdate;
       this.createdfrom = createdfrom;
       this.createddate = createddate;
       this.changedfrom = changedfrom;
       this.changeddate = changeddate;
       this.companymeetingdocs = companymeetingdocs;
       this.companymeetingcontactses = companymeetingcontactses;
    }
   
    public Integer getMeetingprotocolid() {
        return this.meetingprotocolid;
    }
    
    public void setMeetingprotocolid(Integer meetingprotocolid) {
        this.meetingprotocolid = meetingprotocolid;
    }
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    public String getMeetingsubject() {
        return this.meetingsubject;
    }
    
    public void setMeetingsubject(String meetingsubject) {
        this.meetingsubject = meetingsubject;
    }
    public String getMeetingtype() {
        return this.meetingtype;
    }
    
    public void setMeetingtype(String meetingtype) {
        this.meetingtype = meetingtype;
    }
    public String getProtocol() {
        return this.protocol;
    }
    
    public void setProtocol(String protocol) {
        this.protocol = protocol;
    }
    public Date getMetingdate() {
        return this.metingdate;
    }
    
    public void setMetingdate(Date metingdate) {
        this.metingdate = metingdate;
    }
    public String getCreatedfrom() {
        return this.createdfrom;
    }
    
    public void setCreatedfrom(String createdfrom) {
        this.createdfrom = createdfrom;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getChangedfrom() {
        return this.changedfrom;
    }
    
    public void setChangedfrom(String changedfrom) {
        this.changedfrom = changedfrom;
    }
    public Date getChangeddate() {
        return this.changeddate;
    }
    
    public void setChangeddate(Date changeddate) {
        this.changeddate = changeddate;
    }
    public Set<Companymeetingdoc> getCompanymeetingdocs() {
        return this.companymeetingdocs;
    }
    
    public void setCompanymeetingdocs(Set<Companymeetingdoc> companymeetingdocs) {
        this.companymeetingdocs = companymeetingdocs;
    }
    public Set<Companymeetingcontacts> getCompanymeetingcontactses() {
        return this.companymeetingcontactses;
    }
    
    public void setCompanymeetingcontactses(Set<Companymeetingcontacts> companymeetingcontactses) {
        this.companymeetingcontactses = companymeetingcontactses;
    }




}


