package ebiNeutrinoSDK.model.hibernate;
// Generated 23-gen-2012 12.30.18 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Crmcalendar generated by hbm2java
 */
public class Crmcalendar  implements java.io.Serializable {


     private Integer calendarid;
     private String cuser;
     private String name;
     private String color;
     private String description;
     private Date startdate;
     private Date enddate;
     private byte[] cicon;

    public Crmcalendar() {
    }

    public Crmcalendar(String cuser, String name, String color, String description, Date startdate, Date enddate, byte[] cicon) {
       this.cuser = cuser;
       this.name = name;
       this.color = color;
       this.description = description;
       this.startdate = startdate;
       this.enddate = enddate;
       this.cicon = cicon;
    }
   
    public Integer getCalendarid() {
        return this.calendarid;
    }
    
    public void setCalendarid(Integer calendarid) {
        this.calendarid = calendarid;
    }
    public String getCuser() {
        return this.cuser;
    }
    
    public void setCuser(String cuser) {
        this.cuser = cuser;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getStartdate() {
        return this.startdate;
    }
    
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }
    public Date getEnddate() {
        return this.enddate;
    }
    
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }
    public byte[] getCicon() {
        return this.cicon;
    }
    
    public void setCicon(byte[] cicon) {
        this.cicon = cicon;
    }




}


