package ebiNeutrinoSDK.model.hibernate;
// Generated 23-gen-2012 12.30.18 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Crminvoice generated by hbm2java
 */
public class Crminvoice  implements java.io.Serializable {


     private Integer invoiceid;
     private String assosiation;
     private Integer invoicenr;
     private String beginchar;
     private String name;
     private String status;
     private String category;
     private Date date;
     private String taxtype;
     private String gender;
     private String position;
     private String companyname;
     private String contactname;
     private String contactsurname;
     private String contactstreet;
     private String contactzip;
     private String contactlocation;
     private String contactpostcode;
     private String contactcountry;
     private String contacttelephone;
     private String contactfax;
     private String contactemail;
     private String contactweb;
     private String contactdescription;
     private Date createddate;
     private String createdfrom;
     private Date changeddate;
     private String changedfrom;
     private Set<Crminvoiceposition> crminvoicepositions = new HashSet<Crminvoiceposition>(0);

    public Crminvoice() {
    }

    public Crminvoice(String assosiation, Integer invoicenr, String beginchar, String name, String status, String category, Date date, String taxtype, String gender, String position, String companyname, String contactname, String contactsurname, String contactstreet, String contactzip, String contactlocation, String contactpostcode, String contactcountry, String contacttelephone, String contactfax, String contactemail, String contactweb, String contactdescription, Date createddate, String createdfrom, Date changeddate, String changedfrom, Set<Crminvoiceposition> crminvoicepositions) {
       this.assosiation = assosiation;
       this.invoicenr = invoicenr;
       this.beginchar = beginchar;
       this.name = name;
       this.status = status;
       this.category = category;
       this.date = date;
       this.taxtype = taxtype;
       this.gender = gender;
       this.position = position;
       this.companyname = companyname;
       this.contactname = contactname;
       this.contactsurname = contactsurname;
       this.contactstreet = contactstreet;
       this.contactzip = contactzip;
       this.contactlocation = contactlocation;
       this.contactpostcode = contactpostcode;
       this.contactcountry = contactcountry;
       this.contacttelephone = contacttelephone;
       this.contactfax = contactfax;
       this.contactemail = contactemail;
       this.contactweb = contactweb;
       this.contactdescription = contactdescription;
       this.createddate = createddate;
       this.createdfrom = createdfrom;
       this.changeddate = changeddate;
       this.changedfrom = changedfrom;
       this.crminvoicepositions = crminvoicepositions;
    }
   
    public Integer getInvoiceid() {
        return this.invoiceid;
    }
    
    public void setInvoiceid(Integer invoiceid) {
        this.invoiceid = invoiceid;
    }
    public String getAssosiation() {
        return this.assosiation;
    }
    
    public void setAssosiation(String assosiation) {
        this.assosiation = assosiation;
    }
    public Integer getInvoicenr() {
        return this.invoicenr;
    }
    
    public void setInvoicenr(Integer invoicenr) {
        this.invoicenr = invoicenr;
    }
    public String getBeginchar() {
        return this.beginchar;
    }
    
    public void setBeginchar(String beginchar) {
        this.beginchar = beginchar;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getTaxtype() {
        return this.taxtype;
    }
    
    public void setTaxtype(String taxtype) {
        this.taxtype = taxtype;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }
    public String getCompanyname() {
        return this.companyname;
    }
    
    public void setCompanyname(String companyname) {
        this.companyname = companyname;
    }
    public String getContactname() {
        return this.contactname;
    }
    
    public void setContactname(String contactname) {
        this.contactname = contactname;
    }
    public String getContactsurname() {
        return this.contactsurname;
    }
    
    public void setContactsurname(String contactsurname) {
        this.contactsurname = contactsurname;
    }
    public String getContactstreet() {
        return this.contactstreet;
    }
    
    public void setContactstreet(String contactstreet) {
        this.contactstreet = contactstreet;
    }
    public String getContactzip() {
        return this.contactzip;
    }
    
    public void setContactzip(String contactzip) {
        this.contactzip = contactzip;
    }
    public String getContactlocation() {
        return this.contactlocation;
    }
    
    public void setContactlocation(String contactlocation) {
        this.contactlocation = contactlocation;
    }
    public String getContactpostcode() {
        return this.contactpostcode;
    }
    
    public void setContactpostcode(String contactpostcode) {
        this.contactpostcode = contactpostcode;
    }
    public String getContactcountry() {
        return this.contactcountry;
    }
    
    public void setContactcountry(String contactcountry) {
        this.contactcountry = contactcountry;
    }
    public String getContacttelephone() {
        return this.contacttelephone;
    }
    
    public void setContacttelephone(String contacttelephone) {
        this.contacttelephone = contacttelephone;
    }
    public String getContactfax() {
        return this.contactfax;
    }
    
    public void setContactfax(String contactfax) {
        this.contactfax = contactfax;
    }
    public String getContactemail() {
        return this.contactemail;
    }
    
    public void setContactemail(String contactemail) {
        this.contactemail = contactemail;
    }
    public String getContactweb() {
        return this.contactweb;
    }
    
    public void setContactweb(String contactweb) {
        this.contactweb = contactweb;
    }
    public String getContactdescription() {
        return this.contactdescription;
    }
    
    public void setContactdescription(String contactdescription) {
        this.contactdescription = contactdescription;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getCreatedfrom() {
        return this.createdfrom;
    }
    
    public void setCreatedfrom(String createdfrom) {
        this.createdfrom = createdfrom;
    }
    public Date getChangeddate() {
        return this.changeddate;
    }
    
    public void setChangeddate(Date changeddate) {
        this.changeddate = changeddate;
    }
    public String getChangedfrom() {
        return this.changedfrom;
    }
    
    public void setChangedfrom(String changedfrom) {
        this.changedfrom = changedfrom;
    }
    public Set<Crminvoiceposition> getCrminvoicepositions() {
        return this.crminvoicepositions;
    }
    
    public void setCrminvoicepositions(Set<Crminvoiceposition> crminvoicepositions) {
        this.crminvoicepositions = crminvoicepositions;
    }




}


