package ebiNeutrinoSDK.model.hibernate;
// Generated 23-gen-2012 12.30.18 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Crmproblemsolutions generated by hbm2java
 */
public class Crmproblemsolutions  implements java.io.Serializable {


     private Integer prosolid;
     private String servicenr;
     private String name;
     private String classification;
     private String category;
     private String type;
     private String status;
     private String description;
     private String createdfrom;
     private Date createddate;
     private String changedfrom;
     private Date changeddate;
     private Set<Crmproblemsolposition> crmproblemsolpositions = new HashSet<Crmproblemsolposition>(0);
     private Set<Crmproblemsoldocs> crmproblemsoldocses = new HashSet<Crmproblemsoldocs>(0);

    public Crmproblemsolutions() {
    }

    public Crmproblemsolutions(String servicenr, String name, String classification, String category, String type, String status, String description, String createdfrom, Date createddate, String changedfrom, Date changeddate, Set<Crmproblemsolposition> crmproblemsolpositions, Set<Crmproblemsoldocs> crmproblemsoldocses) {
       this.servicenr = servicenr;
       this.name = name;
       this.classification = classification;
       this.category = category;
       this.type = type;
       this.status = status;
       this.description = description;
       this.createdfrom = createdfrom;
       this.createddate = createddate;
       this.changedfrom = changedfrom;
       this.changeddate = changeddate;
       this.crmproblemsolpositions = crmproblemsolpositions;
       this.crmproblemsoldocses = crmproblemsoldocses;
    }
   
    public Integer getProsolid() {
        return this.prosolid;
    }
    
    public void setProsolid(Integer prosolid) {
        this.prosolid = prosolid;
    }
    public String getServicenr() {
        return this.servicenr;
    }
    
    public void setServicenr(String servicenr) {
        this.servicenr = servicenr;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getClassification() {
        return this.classification;
    }
    
    public void setClassification(String classification) {
        this.classification = classification;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getCreatedfrom() {
        return this.createdfrom;
    }
    
    public void setCreatedfrom(String createdfrom) {
        this.createdfrom = createdfrom;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getChangedfrom() {
        return this.changedfrom;
    }
    
    public void setChangedfrom(String changedfrom) {
        this.changedfrom = changedfrom;
    }
    public Date getChangeddate() {
        return this.changeddate;
    }
    
    public void setChangeddate(Date changeddate) {
        this.changeddate = changeddate;
    }
    public Set<Crmproblemsolposition> getCrmproblemsolpositions() {
        return this.crmproblemsolpositions;
    }
    
    public void setCrmproblemsolpositions(Set<Crmproblemsolposition> crmproblemsolpositions) {
        this.crmproblemsolpositions = crmproblemsolpositions;
    }
    public Set<Crmproblemsoldocs> getCrmproblemsoldocses() {
        return this.crmproblemsoldocses;
    }
    
    public void setCrmproblemsoldocses(Set<Crmproblemsoldocs> crmproblemsoldocses) {
        this.crmproblemsoldocses = crmproblemsoldocses;
    }




}


