package ebiNeutrinoSDK.model.hibernate;
import java.util.Date;

/**
 * Crmproduct doc generated by hbm2java
 */
public class Crmproductdocs implements java.io.Serializable {


    private Integer productdocid;
    private Crmproduct product;
    private String name;
    private byte[] files;
    private String createdfrom;
    private Date createddate;

    public Crmproductdocs() {}

    public Crmproductdocs(Crmproduct product, String name, byte[] files, String createdfrom, Date createddate) {
        this.product = product;
        this.name = name;
        this.files = files;
        this.createdfrom = createdfrom;
        this.createddate = createddate;
    }

    public Integer getProductdocid() {
        return this.productdocid;
    }

    public void setProductdocid(Integer productdocid) {
        this.productdocid = productdocid;
    }
    public Crmproduct getCrmproduct() {
        return this.product;
    }

    public void setCrmproduct(Crmproduct product) {
        this.product = product;
    }
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }
    public byte[] getFiles() {
        return this.files;
    }

    public void setFiles(byte[] files) {
        this.files = files;
    }
    public String getCreatedfrom() {
        return this.createdfrom;
    }

    public void setCreatedfrom(String createdfrom) {
        this.createdfrom = createdfrom;
    }
    public Date getCreateddate() {
        return this.createddate;
    }

    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

}


