package ebiNeutrinoSDK.model.hibernate;
// Generated 23-gen-2012 12.30.18 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Crmproblemsolposition generated by hbm2java
 */
public class Crmproblemsolposition  implements java.io.Serializable {


     private Integer productid;
     private Crmproblemsolutions crmproblemsolutions;
     private Date createddate;
     private String createdfrom;
     private Date changeddate;
     private String changedfrom;
     private String productnr;
     private String productname;
     private String category;
     private String type;
     private String taxtype;
     private Double netamount;
     private Double pretax;
     private Integer dipendencyid;
     private Integer dimensionid;
     private byte[] picture;
     private String picturename;
     private String description;

    public Crmproblemsolposition() {
    }

    public Crmproblemsolposition(Crmproblemsolutions crmproblemsolutions, Date createddate, String createdfrom, Date changeddate, String changedfrom, String productnr, String productname, String category, String type, String taxtype, Double netamount, Double pretax, Integer dipendencyid, Integer dimensionid, byte[] picture, String picturename, String description) {
       this.crmproblemsolutions = crmproblemsolutions;
       this.createddate = createddate;
       this.createdfrom = createdfrom;
       this.changeddate = changeddate;
       this.changedfrom = changedfrom;
       this.productnr = productnr;
       this.productname = productname;
       this.category = category;
       this.type = type;
       this.taxtype = taxtype;
       this.netamount = netamount;
       this.pretax = pretax;
       this.dipendencyid = dipendencyid;
       this.dimensionid = dimensionid;
       this.picture = picture;
       this.picturename = picturename;
       this.description = description;
    }
   
    public Integer getProductid() {
        return this.productid;
    }
    
    public void setProductid(Integer productid) {
        this.productid = productid;
    }
    public Crmproblemsolutions getCrmproblemsolutions() {
        return this.crmproblemsolutions;
    }
    
    public void setCrmproblemsolutions(Crmproblemsolutions crmproblemsolutions) {
        this.crmproblemsolutions = crmproblemsolutions;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getCreatedfrom() {
        return this.createdfrom;
    }
    
    public void setCreatedfrom(String createdfrom) {
        this.createdfrom = createdfrom;
    }
    public Date getChangeddate() {
        return this.changeddate;
    }
    
    public void setChangeddate(Date changeddate) {
        this.changeddate = changeddate;
    }
    public String getChangedfrom() {
        return this.changedfrom;
    }
    
    public void setChangedfrom(String changedfrom) {
        this.changedfrom = changedfrom;
    }
    public String getProductnr() {
        return this.productnr;
    }
    
    public void setProductnr(String productnr) {
        this.productnr = productnr;
    }
    public String getProductname() {
        return this.productname;
    }
    
    public void setProductname(String productname) {
        this.productname = productname;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getTaxtype() {
        return this.taxtype;
    }
    
    public void setTaxtype(String taxtype) {
        this.taxtype = taxtype;
    }
    public Double getNetamount() {
        return this.netamount;
    }
    
    public void setNetamount(Double netamount) {
        this.netamount = netamount;
    }
    public Double getPretax() {
        return this.pretax;
    }
    
    public void setPretax(Double pretax) {
        this.pretax = pretax;
    }
    public Integer getDipendencyid() {
        return this.dipendencyid;
    }
    
    public void setDipendencyid(Integer dipendencyid) {
        this.dipendencyid = dipendencyid;
    }
    public Integer getDimensionid() {
        return this.dimensionid;
    }
    
    public void setDimensionid(Integer dimensionid) {
        this.dimensionid = dimensionid;
    }
    public byte[] getPicture() {
        return this.picture;
    }
    
    public void setPicture(byte[] picture) {
        this.picture = picture;
    }
    public String getPicturename() {
        return this.picturename;
    }
    
    public void setPicturename(String picturename) {
        this.picturename = picturename;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


