package ebiNeutrinoSDK.model.hibernate;
// Generated 23-gen-2012 12.30.18 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Crmprojectcost generated by hbm2java
 */
public class Crmprojectcost  implements java.io.Serializable {


     private Integer costid;
     private Crmprojecttask crmprojecttask;
     private Date createddate;
     private String createdfrom;
     private Date changeddate;
     private String changedfrom;
     private String name;
     private Double value;

    public Crmprojectcost() {
    }

    public Crmprojectcost(Crmprojecttask crmprojecttask, Date createddate, String createdfrom, Date changeddate, String changedfrom, String name, Double value) {
       this.crmprojecttask = crmprojecttask;
       this.createddate = createddate;
       this.createdfrom = createdfrom;
       this.changeddate = changeddate;
       this.changedfrom = changedfrom;
       this.name = name;
       this.value = value;
    }
   
    public Integer getCostid() {
        return this.costid;
    }
    
    public void setCostid(Integer costid) {
        this.costid = costid;
    }
    public Crmprojecttask getCrmprojecttask() {
        return this.crmprojecttask;
    }
    
    public void setCrmprojecttask(Crmprojecttask crmprojecttask) {
        this.crmprojecttask = crmprojecttask;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getCreatedfrom() {
        return this.createdfrom;
    }
    
    public void setCreatedfrom(String createdfrom) {
        this.createdfrom = createdfrom;
    }
    public Date getChangeddate() {
        return this.changeddate;
    }
    
    public void setChangeddate(Date changeddate) {
        this.changeddate = changeddate;
    }
    public String getChangedfrom() {
        return this.changedfrom;
    }
    
    public void setChangedfrom(String changedfrom) {
        this.changedfrom = changedfrom;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Double getValue() {
        return this.value;
    }
    
    public void setValue(Double value) {
        this.value = value;
    }




}


