package ebiNeutrinoSDK.model.hibernate;
// Generated 14.11.2011 11:29:58 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Crmtimertasks generated by hbm2java
 */
public class Crmtimertasks  implements java.io.Serializable {


     private Integer timerid;
     private String createdfor;
     private Date createddate;
     private Integer timerstart;
     private Integer timerduration;
     private Integer timerstatus;
     private Integer tasktype;
     private Date timertime;
     private String module;
     private Integer recordid;
     private String executecode;
     private Integer extra;

    public Crmtimertasks() {
    }

    public Crmtimertasks(String createdfor, Date createddate, Integer timerstart, Integer timerduration, Integer timerstatus, Integer tasktype, Date timertime, String module, Integer recordid, String executecode, Integer extra) {
       this.createdfor = createdfor;
       this.createddate = createddate;
       this.timerstart = timerstart;
       this.timerduration = timerduration;
       this.timerstatus = timerstatus;
       this.tasktype = tasktype;
       this.timertime = timertime;
       this.module = module;
       this.recordid = recordid;
       this.executecode = executecode;
       this.extra = extra;
    }
   
    public Integer getTimerid() {
        return this.timerid;
    }
    
    public void setTimerid(Integer timerid) {
        this.timerid = timerid;
    }
    public String getCreatedfor() {
        return this.createdfor;
    }
    
    public void setCreatedfor(String createdfor) {
        this.createdfor = createdfor;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public Integer getTimerstart() {
        return this.timerstart;
    }
    
    public void setTimerstart(Integer timerstart) {
        this.timerstart = timerstart;
    }
    public Integer getTimerduration() {
        return this.timerduration;
    }
    
    public void setTimerduration(Integer timerduration) {
        this.timerduration = timerduration;
    }
    public Integer getTimerstatus() {
        return this.timerstatus;
    }
    
    public void setTimerstatus(Integer timerstatus) {
        this.timerstatus = timerstatus;
    }
    public Integer getTasktype() {
        return this.tasktype;
    }
    
    public void setTasktype(Integer tasktype) {
        this.tasktype = tasktype;
    }
    public Date getTimertime() {
        return this.timertime;
    }
    
    public void setTimertime(Date timertime) {
        this.timertime = timertime;
    }
    public String getModule() {
        return this.module;
    }
    
    public void setModule(String module) {
        this.module = module;
    }
    public Integer getRecordid() {
        return this.recordid;
    }
    
    public void setRecordid(Integer recordid) {
        this.recordid = recordid;
    }
    public String getExecutecode() {
        return this.executecode;
    }
    
    public void setExecutecode(String executecode) {
        this.executecode = executecode;
    }
    public Integer getExtra() {
        return this.extra;
    }
    
    public void setExtra(Integer extra) {
        this.extra = extra;
    }




}


