package ebiNeutrinoSDK.model.hibernate;
// Generated 23-gen-2012 12.30.18 by Hibernate Tools 3.4.0.CR1



/**
 * Ebidatastore generated by hbm2java
 */
public class Ebidatastore  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String text;
     private String extra;

    public Ebidatastore() {
    }

    public Ebidatastore(String name, String text, String extra) {
       this.name = name;
       this.text = text;
       this.extra = extra;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public String getExtra() {
        return this.extra;
    }
    
    public void setExtra(String extra) {
        this.extra = extra;
    }




}


