package ebiNeutrinoSDK.model.hibernate;
// Generated 23-gen-2012 12.30.18 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SetReportformodule generated by hbm2java
 */
public class SetReportformodule  implements java.io.Serializable {


     private Integer idreportformodule;
     private String reportname;
     private String reportcategory;
     private String reportfilename;
     private Date reportdate;
     private Boolean showaspdf;
     private Boolean showaswindow;
     private Boolean printauto;
     private Boolean isactive;
     private Set<SetReportparameter> setReportparameters = new HashSet<SetReportparameter>(0);

    public SetReportformodule() {
    }

    public SetReportformodule(String reportname, String reportcategory, String reportfilename, Date reportdate, Boolean showaspdf, Boolean showaswindow, Boolean printauto, Boolean isactive, Set<SetReportparameter> setReportparameters) {
       this.reportname = reportname;
       this.reportcategory = reportcategory;
       this.reportfilename = reportfilename;
       this.reportdate = reportdate;
       this.showaspdf = showaspdf;
       this.showaswindow = showaswindow;
       this.printauto = printauto;
       this.isactive = isactive;
       this.setReportparameters = setReportparameters;
    }
   
    public Integer getIdreportformodule() {
        return this.idreportformodule;
    }
    
    public void setIdreportformodule(Integer idreportformodule) {
        this.idreportformodule = idreportformodule;
    }
    public String getReportname() {
        return this.reportname;
    }
    
    public void setReportname(String reportname) {
        this.reportname = reportname;
    }
    public String getReportcategory() {
        return this.reportcategory;
    }
    
    public void setReportcategory(String reportcategory) {
        this.reportcategory = reportcategory;
    }
    public String getReportfilename() {
        return this.reportfilename;
    }
    
    public void setReportfilename(String reportfilename) {
        this.reportfilename = reportfilename;
    }
    public Date getReportdate() {
        return this.reportdate;
    }
    
    public void setReportdate(Date reportdate) {
        this.reportdate = reportdate;
    }
    public Boolean getShowaspdf() {
        return this.showaspdf;
    }
    
    public void setShowaspdf(Boolean showaspdf) {
        this.showaspdf = showaspdf;
    }
    public Boolean getShowaswindow() {
        return this.showaswindow;
    }
    
    public void setShowaswindow(Boolean showaswindow) {
        this.showaswindow = showaswindow;
    }
    public Boolean getPrintauto() {
        return this.printauto;
    }
    
    public void setPrintauto(Boolean printauto) {
        this.printauto = printauto;
    }
    public Boolean getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(Boolean isactive) {
        this.isactive = isactive;
    }
    public Set<SetReportparameter> getSetReportparameters() {
        return this.setReportparameters;
    }
    
    public void setSetReportparameters(Set<SetReportparameter> setReportparameters) {
        this.setReportparameters = setReportparameters;
    }




}


