package ebiNeutrinoSDK.model.hibernate;
// Generated 23-gen-2012 12.30.18 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Companyservice generated by hbm2java
 */
public class Companyservice  implements java.io.Serializable {


     private Integer serviceid;
     private Company company;
     private String servicenr;
     private String name;
     private String category;
     private String type;
     private String status;
     private String description;
     private String createdfrom;
     private Date createddate;
     private String changedfrom;
     private Date changeddate;
     private Set<Companyservicedocs> companyservicedocses = new HashSet<Companyservicedocs>(0);
     private Set<Companyservicepsol> companyservicepsols = new HashSet<Companyservicepsol>(0);
     private Set<Companyservicepositions> companyservicepositionses = new HashSet<Companyservicepositions>(0);

    public Companyservice() {
    }

    public Companyservice(Company company, String servicenr, String name, String category, String type, String status, String description, String createdfrom, Date createddate, String changedfrom, Date changeddate, Set<Companyservicedocs> companyservicedocses, Set<Companyservicepsol> companyservicepsols, Set<Companyservicepositions> companyservicepositionses) {
       this.company = company;
       this.servicenr = servicenr;
       this.name = name;
       this.category = category;
       this.type = type;
       this.status = status;
       this.description = description;
       this.createdfrom = createdfrom;
       this.createddate = createddate;
       this.changedfrom = changedfrom;
       this.changeddate = changeddate;
       this.companyservicedocses = companyservicedocses;
       this.companyservicepsols = companyservicepsols;
       this.companyservicepositionses = companyservicepositionses;
    }
   
    public Integer getServiceid() {
        return this.serviceid;
    }
    
    public void setServiceid(Integer serviceid) {
        this.serviceid = serviceid;
    }
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    public String getServicenr() {
        return this.servicenr;
    }
    
    public void setServicenr(String servicenr) {
        this.servicenr = servicenr;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getCreatedfrom() {
        return this.createdfrom;
    }
    
    public void setCreatedfrom(String createdfrom) {
        this.createdfrom = createdfrom;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getChangedfrom() {
        return this.changedfrom;
    }
    
    public void setChangedfrom(String changedfrom) {
        this.changedfrom = changedfrom;
    }
    public Date getChangeddate() {
        return this.changeddate;
    }
    
    public void setChangeddate(Date changeddate) {
        this.changeddate = changeddate;
    }
    public Set<Companyservicedocs> getCompanyservicedocses() {
        return this.companyservicedocses;
    }
    
    public void setCompanyservicedocses(Set<Companyservicedocs> companyservicedocses) {
        this.companyservicedocses = companyservicedocses;
    }
    public Set<Companyservicepsol> getCompanyservicepsols() {
        return this.companyservicepsols;
    }
    
    public void setCompanyservicepsols(Set<Companyservicepsol> companyservicepsols) {
        this.companyservicepsols = companyservicepsols;
    }
    public Set<Companyservicepositions> getCompanyservicepositionses() {
        return this.companyservicepositionses;
    }
    
    public void setCompanyservicepositionses(Set<Companyservicepositions> companyservicepositionses) {
        this.companyservicepositionses = companyservicepositionses;
    }




}


