package ebiNeutrinoSDK.model.hibernate;
// Generated 23-gen-2012 12.30.18 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Companymeetingcontacts generated by hbm2java
 */
public class Companymeetingcontacts  implements java.io.Serializable {


     private Integer meetingcontactid;
     private Companymeetingprotocol companymeetingprotocol;
     private Integer pos;
     private String gender;
     private String surname;
     private String name;
     private String mittelname;
     private String position;
     private Date birddate;
     private String phone;
     private String fax;
     private String mobile;
     private String email;
     private String street;
     private String location;
     private String zip;
     private String country;
     private String pbox;
     private String description;
     private String createdfrom;
     private Date createddate;
     private String changedfrom;
     private Date changeddate;

    public Companymeetingcontacts() {
    }

	
    public Companymeetingcontacts(Date createddate) {
        this.createddate = createddate;
    }
    public Companymeetingcontacts(Companymeetingprotocol companymeetingprotocol, Integer pos, String gender, String surname, String name, String mittelname, String position, Date birddate, String phone, String fax, String mobile, String email, String street, String location, String zip, String country, String pbox, String description, String createdfrom, Date createddate, String changedfrom, Date changeddate) {
       this.companymeetingprotocol = companymeetingprotocol;
       this.pos = pos;
       this.gender = gender;
       this.surname = surname;
       this.name = name;
       this.mittelname = mittelname;
       this.position = position;
       this.birddate = birddate;
       this.phone = phone;
       this.fax = fax;
       this.mobile = mobile;
       this.email = email;
       this.street = street;
       this.location = location;
       this.zip = zip;
       this.country = country;
       this.pbox = pbox;
       this.description = description;
       this.createdfrom = createdfrom;
       this.createddate = createddate;
       this.changedfrom = changedfrom;
       this.changeddate = changeddate;
    }
   
    public Integer getMeetingcontactid() {
        return this.meetingcontactid;
    }
    
    public void setMeetingcontactid(Integer meetingcontactid) {
        this.meetingcontactid = meetingcontactid;
    }
    public Companymeetingprotocol getCompanymeetingprotocol() {
        return this.companymeetingprotocol;
    }
    
    public void setCompanymeetingprotocol(Companymeetingprotocol companymeetingprotocol) {
        this.companymeetingprotocol = companymeetingprotocol;
    }
    public Integer getPos() {
        return this.pos;
    }
    
    public void setPos(Integer pos) {
        this.pos = pos;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getMittelname() {
        return this.mittelname;
    }
    
    public void setMittelname(String mittelname) {
        this.mittelname = mittelname;
    }
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }
    public Date getBirddate() {
        return this.birddate;
    }
    
    public void setBirddate(Date birddate) {
        this.birddate = birddate;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public String getZip() {
        return this.zip;
    }
    
    public void setZip(String zip) {
        this.zip = zip;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getPbox() {
        return this.pbox;
    }
    
    public void setPbox(String pbox) {
        this.pbox = pbox;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getCreatedfrom() {
        return this.createdfrom;
    }
    
    public void setCreatedfrom(String createdfrom) {
        this.createdfrom = createdfrom;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getChangedfrom() {
        return this.changedfrom;
    }
    
    public void setChangedfrom(String changedfrom) {
        this.changedfrom = changedfrom;
    }
    public Date getChangeddate() {
        return this.changeddate;
    }
    
    public void setChangeddate(Date changeddate) {
        this.changeddate = changeddate;
    }




}


