package ebiNeutrinoSDK.model.hibernate;
// Generated 23-gen-2012 12.30.18 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Companyservicedocs generated by hbm2java
 */
public class Companyservicedocs  implements java.io.Serializable {


     private Integer servicedocid;
     private Companyservice companyservice;
     private String name;
     private byte[] files;
     private String createdfrom;
     private Date createddate;

    public Companyservicedocs() {
    }

    public Companyservicedocs(Companyservice companyservice, String name, byte[] files, String createdfrom, Date createddate) {
       this.companyservice = companyservice;
       this.name = name;
       this.files = files;
       this.createdfrom = createdfrom;
       this.createddate = createddate;
    }
   
    public Integer getServicedocid() {
        return this.servicedocid;
    }
    
    public void setServicedocid(Integer servicedocid) {
        this.servicedocid = servicedocid;
    }
    public Companyservice getCompanyservice() {
        return this.companyservice;
    }
    
    public void setCompanyservice(Companyservice companyservice) {
        this.companyservice = companyservice;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public byte[] getFiles() {
        return this.files;
    }
    
    public void setFiles(byte[] files) {
        this.files = files;
    }
    public String getCreatedfrom() {
        return this.createdfrom;
    }
    
    public void setCreatedfrom(String createdfrom) {
        this.createdfrom = createdfrom;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }




}


