package ebiNeutrinoSDK.model.hibernate;
// Generated 23-gen-2012 12.30.18 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Companyoffer generated by hbm2java
 */
public class Companyoffer  implements java.io.Serializable {


     private Integer offerid;
     private Company company;
     private Integer opportunityid;
     private String offernr;
     private String name;
     private String status;
     private Integer offerversion;
     private Date offerdate;
     private Date validto;
     private Boolean isrecieved;
     private String description;
     private String createdfrom;
     private Date createddate;
     private String changedfrom;
     private Date changeddate;
     private Set<Companyofferdocs> companyofferdocses = new HashSet<Companyofferdocs>(0);
     private Set<Companyofferreceiver> companyofferreceivers = new HashSet<Companyofferreceiver>(0);
     private Set<Companyofferpositions> companyofferpositionses = new HashSet<Companyofferpositions>(0);

    public Companyoffer() {
    }

	
    public Companyoffer(String offernr) {
        this.offernr = offernr;
    }
    public Companyoffer(Company company, Integer opportunityid, String offernr, String name, String status, Integer offerversion, Date offerdate, Date validto, Boolean isrecieved, String description, String createdfrom, Date createddate, String changedfrom, Date changeddate, Set<Companyofferdocs> companyofferdocses, Set<Companyofferreceiver> companyofferreceivers, Set<Companyofferpositions> companyofferpositionses) {
       this.company = company;
       this.opportunityid = opportunityid;
       this.offernr = offernr;
       this.name = name;
       this.status = status;
       this.offerversion = offerversion;
       this.offerdate = offerdate;
       this.validto = validto;
       this.isrecieved = isrecieved;
       this.description = description;
       this.createdfrom = createdfrom;
       this.createddate = createddate;
       this.changedfrom = changedfrom;
       this.changeddate = changeddate;
       this.companyofferdocses = companyofferdocses;
       this.companyofferreceivers = companyofferreceivers;
       this.companyofferpositionses = companyofferpositionses;
    }
   
    public Integer getOfferid() {
        return this.offerid;
    }
    
    public void setOfferid(Integer offerid) {
        this.offerid = offerid;
    }
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    public Integer getOpportunityid() {
        return this.opportunityid;
    }
    
    public void setOpportunityid(Integer opportunityid) {
        this.opportunityid = opportunityid;
    }
    public String getOffernr() {
        return this.offernr;
    }
    
    public void setOffernr(String offernr) {
        this.offernr = offernr;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Integer getOfferversion() {
        return this.offerversion;
    }
    
    public void setOfferversion(Integer offerversion) {
        this.offerversion = offerversion;
    }
    public Date getOfferdate() {
        return this.offerdate;
    }
    
    public void setOfferdate(Date offerdate) {
        this.offerdate = offerdate;
    }
    public Date getValidto() {
        return this.validto;
    }
    
    public void setValidto(Date validto) {
        this.validto = validto;
    }
    public Boolean getIsrecieved() {
        return this.isrecieved;
    }
    
    public void setIsrecieved(Boolean isrecieved) {
        this.isrecieved = isrecieved;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getCreatedfrom() {
        return this.createdfrom;
    }
    
    public void setCreatedfrom(String createdfrom) {
        this.createdfrom = createdfrom;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getChangedfrom() {
        return this.changedfrom;
    }
    
    public void setChangedfrom(String changedfrom) {
        this.changedfrom = changedfrom;
    }
    public Date getChangeddate() {
        return this.changeddate;
    }
    
    public void setChangeddate(Date changeddate) {
        this.changeddate = changeddate;
    }
    public Set<Companyofferdocs> getCompanyofferdocses() {
        return this.companyofferdocses;
    }
    
    public void setCompanyofferdocses(Set<Companyofferdocs> companyofferdocses) {
        this.companyofferdocses = companyofferdocses;
    }
    public Set<Companyofferreceiver> getCompanyofferreceivers() {
        return this.companyofferreceivers;
    }
    
    public void setCompanyofferreceivers(Set<Companyofferreceiver> companyofferreceivers) {
        this.companyofferreceivers = companyofferreceivers;
    }
    public Set<Companyofferpositions> getCompanyofferpositionses() {
        return this.companyofferpositionses;
    }
    
    public void setCompanyofferpositionses(Set<Companyofferpositions> companyofferpositionses) {
        this.companyofferpositionses = companyofferpositionses;
    }




}


