package ebiNeutrinoSDK.model.hibernate;
// Generated 23-gen-2012 12.30.18 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Companyopporunitydocs generated by hbm2java
 */
public class Companyopporunitydocs  implements java.io.Serializable {


     private Integer docid;
     private Companyopportunity companyopportunity;
     private String name;
     private byte[] files;
     private Date createddate;
     private String createdfrom;

    public Companyopporunitydocs() {
    }

    public Companyopporunitydocs(Companyopportunity companyopportunity, String name, byte[] files, Date createddate, String createdfrom) {
       this.companyopportunity = companyopportunity;
       this.name = name;
       this.files = files;
       this.createddate = createddate;
       this.createdfrom = createdfrom;
    }
   
    public Integer getDocid() {
        return this.docid;
    }
    
    public void setDocid(Integer docid) {
        this.docid = docid;
    }
    public Companyopportunity getCompanyopportunity() {
        return this.companyopportunity;
    }
    
    public void setCompanyopportunity(Companyopportunity companyopportunity) {
        this.companyopportunity = companyopportunity;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public byte[] getFiles() {
        return this.files;
    }
    
    public void setFiles(byte[] files) {
        this.files = files;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getCreatedfrom() {
        return this.createdfrom;
    }
    
    public void setCreatedfrom(String createdfrom) {
        this.createdfrom = createdfrom;
    }




}


