package ebiNeutrinoSDK.model.hibernate;
// Generated 23-gen-2012 12.30.18 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Companycontacts generated by hbm2java
 */
public class Companycontacts  implements java.io.Serializable {


     private Integer contactid;
     private Company company;
     private Boolean maincontact;
     private String gender;
     private String title;
     private String surname;
     private String name;
     private String mittelname;
     private String position;
     private Date birddate;
     private String phone;
     private String fax;
     private String mobile;
     private String email;
     private String description;
     private String createdfrom;
     private Date createddate;
     private String changedfrom;
     private Date changeddate;
     private Set<Companycontactaddress> companycontactaddresses = new HashSet<Companycontactaddress>(0);

    public Companycontacts() {
    }

	
    public Companycontacts(Company company) {
        this.company = company;
    }
    public Companycontacts(Company company, Boolean maincontact, String gender, String title, String surname, String name, String mittelname, String position, Date birddate, String phone, String fax, String mobile, String email, String description, String createdfrom, Date createddate, String changedfrom, Date changeddate, Set<Companycontactaddress> companycontactaddresses) {
       this.company = company;
       this.maincontact = maincontact;
       this.gender = gender;
       this.title = title;
       this.surname = surname;
       this.name = name;
       this.mittelname = mittelname;
       this.position = position;
       this.birddate = birddate;
       this.phone = phone;
       this.fax = fax;
       this.mobile = mobile;
       this.email = email;
       this.description = description;
       this.createdfrom = createdfrom;
       this.createddate = createddate;
       this.changedfrom = changedfrom;
       this.changeddate = changeddate;
       this.companycontactaddresses = companycontactaddresses;
    }
   
    public Integer getContactid() {
        return this.contactid;
    }
    
    public void setContactid(Integer contactid) {
        this.contactid = contactid;
    }
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    public Boolean getMaincontact() {
        return this.maincontact;
    }
    
    public void setMaincontact(Boolean maincontact) {
        this.maincontact = maincontact;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getMittelname() {
        return this.mittelname;
    }
    
    public void setMittelname(String mittelname) {
        this.mittelname = mittelname;
    }
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }
    public Date getBirddate() {
        return this.birddate;
    }
    
    public void setBirddate(Date birddate) {
        this.birddate = birddate;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getCreatedfrom() {
        return this.createdfrom;
    }
    
    public void setCreatedfrom(String createdfrom) {
        this.createdfrom = createdfrom;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getChangedfrom() {
        return this.changedfrom;
    }
    
    public void setChangedfrom(String changedfrom) {
        this.changedfrom = changedfrom;
    }
    public Date getChangeddate() {
        return this.changeddate;
    }
    
    public void setChangeddate(Date changeddate) {
        this.changeddate = changeddate;
    }
    public Set<Companycontactaddress> getCompanycontactaddresses() {
        return this.companycontactaddresses;
    }
    
    public void setCompanycontactaddresses(Set<Companycontactaddress> companycontactaddresses) {
        this.companycontactaddresses = companycontactaddresses;
    }




}


