package ebiNeutrinoSDK.model.hibernate;
// Generated 23-gen-2012 12.30.18 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Companyofferdocs generated by hbm2java
 */
public class Companyofferdocs  implements java.io.Serializable {


     private Integer offerdocid;
     private Companyoffer companyoffer;
     private String name;
     private byte[] files;
     private Date createddate;
     private String createdfrom;

    public Companyofferdocs() {
    }

    public Companyofferdocs(Companyoffer companyoffer, String name, byte[] files, Date createddate, String createdfrom) {
       this.companyoffer = companyoffer;
       this.name = name;
       this.files = files;
       this.createddate = createddate;
       this.createdfrom = createdfrom;
    }
   
    public Integer getOfferdocid() {
        return this.offerdocid;
    }
    
    public void setOfferdocid(Integer offerdocid) {
        this.offerdocid = offerdocid;
    }
    public Companyoffer getCompanyoffer() {
        return this.companyoffer;
    }
    
    public void setCompanyoffer(Companyoffer companyoffer) {
        this.companyoffer = companyoffer;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public byte[] getFiles() {
        return this.files;
    }
    
    public void setFiles(byte[] files) {
        this.files = files;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getCreatedfrom() {
        return this.createdfrom;
    }
    
    public void setCreatedfrom(String createdfrom) {
        this.createdfrom = createdfrom;
    }




}


