package ebiNeutrinoSDK.model.hibernate;
// Generated 23-gen-2012 12.30.18 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Crmcampaignprop generated by hbm2java
 */
public class Crmcampaignprop  implements java.io.Serializable {


     private Integer propertiesid;
     private Crmcampaign crmcampaign;
     private Date createddate;
     private String createdfrom;
     private Date changeddate;
     private String changedfrom;
     private String name;
     private String value;

    public Crmcampaignprop() {
    }

    public Crmcampaignprop(Crmcampaign crmcampaign, Date createddate, String createdfrom, Date changeddate, String changedfrom, String name, String value) {
       this.crmcampaign = crmcampaign;
       this.createddate = createddate;
       this.createdfrom = createdfrom;
       this.changeddate = changeddate;
       this.changedfrom = changedfrom;
       this.name = name;
       this.value = value;
    }
   
    public Integer getPropertiesid() {
        return this.propertiesid;
    }
    
    public void setPropertiesid(Integer propertiesid) {
        this.propertiesid = propertiesid;
    }
    public Crmcampaign getCrmcampaign() {
        return this.crmcampaign;
    }
    
    public void setCrmcampaign(Crmcampaign crmcampaign) {
        this.crmcampaign = crmcampaign;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getCreatedfrom() {
        return this.createdfrom;
    }
    
    public void setCreatedfrom(String createdfrom) {
        this.createdfrom = createdfrom;
    }
    public Date getChangeddate() {
        return this.changeddate;
    }
    
    public void setChangeddate(Date changeddate) {
        this.changeddate = changeddate;
    }
    public String getChangedfrom() {
        return this.changedfrom;
    }
    
    public void setChangedfrom(String changedfrom) {
        this.changedfrom = changedfrom;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


