package ebiNeutrinoSDK.model.hibernate;
// Generated 23-gen-2012 12.30.18 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Crmcampaign generated by hbm2java
 */
public class Crmcampaign  implements java.io.Serializable {


     private Integer campaignid;
     private String campaignnr;
     private Date createddate;
     private String createdfrom;
     private Date changeddate;
     private String changedfrom;
     private String name;
     private String status;
     private Date validfrom;
     private Date validto;
     private Set<Crmcampaignprop> crmcampaignprops = new HashSet<Crmcampaignprop>(0);
     private Set<Crmcampaignposition> crmcampaignpositions = new HashSet<Crmcampaignposition>(0);
     private Set<Crmcampaigndocs> crmcampaigndocses = new HashSet<Crmcampaigndocs>(0);
     private Set<Crmcampaignreceiver> crmcampaignreceivers = new HashSet<Crmcampaignreceiver>(0);

    public Crmcampaign() {
    }

    public Crmcampaign(String campaignnr, Date createddate, String createdfrom, Date changeddate, String changedfrom, String name, String status, Date validfrom, Date validto, Set<Crmcampaignprop> crmcampaignprops, Set<Crmcampaignposition> crmcampaignpositions, Set<Crmcampaigndocs> crmcampaigndocses, Set<Crmcampaignreceiver> crmcampaignreceivers) {
       this.campaignnr = campaignnr;
       this.createddate = createddate;
       this.createdfrom = createdfrom;
       this.changeddate = changeddate;
       this.changedfrom = changedfrom;
       this.name = name;
       this.status = status;
       this.validfrom = validfrom;
       this.validto = validto;
       this.crmcampaignprops = crmcampaignprops;
       this.crmcampaignpositions = crmcampaignpositions;
       this.crmcampaigndocses = crmcampaigndocses;
       this.crmcampaignreceivers = crmcampaignreceivers;
    }
   
    public Integer getCampaignid() {
        return this.campaignid;
    }
    
    public void setCampaignid(Integer campaignid) {
        this.campaignid = campaignid;
    }
    public String getCampaignnr() {
        return this.campaignnr;
    }
    
    public void setCampaignnr(String campaignnr) {
        this.campaignnr = campaignnr;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getCreatedfrom() {
        return this.createdfrom;
    }
    
    public void setCreatedfrom(String createdfrom) {
        this.createdfrom = createdfrom;
    }
    public Date getChangeddate() {
        return this.changeddate;
    }
    
    public void setChangeddate(Date changeddate) {
        this.changeddate = changeddate;
    }
    public String getChangedfrom() {
        return this.changedfrom;
    }
    
    public void setChangedfrom(String changedfrom) {
        this.changedfrom = changedfrom;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getValidfrom() {
        return this.validfrom;
    }
    
    public void setValidfrom(Date validfrom) {
        this.validfrom = validfrom;
    }
    public Date getValidto() {
        return this.validto;
    }
    
    public void setValidto(Date validto) {
        this.validto = validto;
    }
    public Set<Crmcampaignprop> getCrmcampaignprops() {
        return this.crmcampaignprops;
    }
    
    public void setCrmcampaignprops(Set<Crmcampaignprop> crmcampaignprops) {
        this.crmcampaignprops = crmcampaignprops;
    }
    public Set<Crmcampaignposition> getCrmcampaignpositions() {
        return this.crmcampaignpositions;
    }
    
    public void setCrmcampaignpositions(Set<Crmcampaignposition> crmcampaignpositions) {
        this.crmcampaignpositions = crmcampaignpositions;
    }
    public Set<Crmcampaigndocs> getCrmcampaigndocses() {
        return this.crmcampaigndocses;
    }
    
    public void setCrmcampaigndocses(Set<Crmcampaigndocs> crmcampaigndocses) {
        this.crmcampaigndocses = crmcampaigndocses;
    }
    public Set<Crmcampaignreceiver> getCrmcampaignreceivers() {
        return this.crmcampaignreceivers;
    }
    
    public void setCrmcampaignreceivers(Set<Crmcampaignreceiver> crmcampaignreceivers) {
        this.crmcampaignreceivers = crmcampaignreceivers;
    }




}


