package ebiNeutrinoSDK.model.hibernate;
// Generated 23-gen-2012 12.30.18 by Hibernate Tools 3.4.0.CR1



/**
 * Crminvoicenumber generated by hbm2java
 */
public class Crminvoicenumber  implements java.io.Serializable {


     private Integer id;
     private Crminvoicecategory crminvoicecategory;
     private String category;
     private String beginchar;
     private Integer numberfrom;
     private Integer numberto;

    public Crminvoicenumber() {
    }

    public Crminvoicenumber(Crminvoicecategory crminvoicecategory, String category, String beginchar, Integer numberfrom, Integer numberto) {
       this.crminvoicecategory = crminvoicecategory;
       this.category = category;
       this.beginchar = beginchar;
       this.numberfrom = numberfrom;
       this.numberto = numberto;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Crminvoicecategory getCrminvoicecategory() {
        return this.crminvoicecategory;
    }
    
    public void setCrminvoicecategory(Crminvoicecategory crminvoicecategory) {
        this.crminvoicecategory = crminvoicecategory;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public String getBeginchar() {
        return this.beginchar;
    }
    
    public void setBeginchar(String beginchar) {
        this.beginchar = beginchar;
    }
    public Integer getNumberfrom() {
        return this.numberfrom;
    }
    
    public void setNumberfrom(Integer numberfrom) {
        this.numberfrom = numberfrom;
    }
    public Integer getNumberto() {
        return this.numberto;
    }
    
    public void setNumberto(Integer numberto) {
        this.numberto = numberto;
    }




}


