package ebiNeutrinoSDK.model.hibernate;
// Generated 23-gen-2012 12.30.18 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * Crminvoicecategory generated by hbm2java
 */
public class Crminvoicecategory  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set<Crminvoicenumber> crminvoicenumbers = new HashSet<Crminvoicenumber>(0);

    public Crminvoicecategory() {
    }

    public Crminvoicecategory(String name, Set<Crminvoicenumber> crminvoicenumbers) {
       this.name = name;
       this.crminvoicenumbers = crminvoicenumbers;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<Crminvoicenumber> getCrminvoicenumbers() {
        return this.crminvoicenumbers;
    }
    
    public void setCrminvoicenumbers(Set<Crminvoicenumber> crminvoicenumbers) {
        this.crminvoicenumbers = crminvoicenumbers;
    }




}


