package ebiNeutrinoSDK.model.hibernate;
// Generated 23-gen-2012 12.30.18 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Crmproductdependency generated by hbm2java
 */
public class Crmproductdependency  implements java.io.Serializable {


     private Integer dependencyid;
     private Crmproduct crmproduct;
     private Integer productidid;
     private Date createddate;
     private String createdfrom;
     private Date changeddate;
     private String changedfrom;
     private String productnr;
     private String productname;

    public Crmproductdependency() {
    }

    public Crmproductdependency(Crmproduct crmproduct, Integer productidid, Date createddate, String createdfrom, Date changeddate, String changedfrom, String productnr, String productname) {
       this.crmproduct = crmproduct;
       this.productidid = productidid;
       this.createddate = createddate;
       this.createdfrom = createdfrom;
       this.changeddate = changeddate;
       this.changedfrom = changedfrom;
       this.productnr = productnr;
       this.productname = productname;
    }
   
    public Integer getDependencyid() {
        return this.dependencyid;
    }
    
    public void setDependencyid(Integer dependencyid) {
        this.dependencyid = dependencyid;
    }
    public Crmproduct getCrmproduct() {
        return this.crmproduct;
    }
    
    public void setCrmproduct(Crmproduct crmproduct) {
        this.crmproduct = crmproduct;
    }
    public Integer getProductidid() {
        return this.productidid;
    }
    
    public void setProductidid(Integer productidid) {
        this.productidid = productidid;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getCreatedfrom() {
        return this.createdfrom;
    }
    
    public void setCreatedfrom(String createdfrom) {
        this.createdfrom = createdfrom;
    }
    public Date getChangeddate() {
        return this.changeddate;
    }
    
    public void setChangeddate(Date changeddate) {
        this.changeddate = changeddate;
    }
    public String getChangedfrom() {
        return this.changedfrom;
    }
    
    public void setChangedfrom(String changedfrom) {
        this.changedfrom = changedfrom;
    }
    public String getProductnr() {
        return this.productnr;
    }
    
    public void setProductnr(String productnr) {
        this.productnr = productnr;
    }
    public String getProductname() {
        return this.productname;
    }
    
    public void setProductname(String productname) {
        this.productname = productname;
    }




}


