package ebiNeutrinoSDK.model.hibernate;
// Generated 23-gen-2012 12.30.18 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Ebicrmhistory generated by hbm2java
 */
public class Ebicrmhistory  implements java.io.Serializable {


     private Integer historyid;
     private Integer companyid;
     private String category;
     private String changedvalue;
     private String changedfrom;
     private Date changeddate;

    public Ebicrmhistory() {
    }

    public Ebicrmhistory(Integer companyid, String category, String changedvalue, String changedfrom, Date changeddate) {
       this.companyid = companyid;
       this.category = category;
       this.changedvalue = changedvalue;
       this.changedfrom = changedfrom;
       this.changeddate = changeddate;
    }
   
    public Integer getHistoryid() {
        return this.historyid;
    }
    
    public void setHistoryid(Integer historyid) {
        this.historyid = historyid;
    }
    public Integer getCompanyid() {
        return this.companyid;
    }
    
    public void setCompanyid(Integer companyid) {
        this.companyid = companyid;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public String getChangedvalue() {
        return this.changedvalue;
    }
    
    public void setChangedvalue(String changedvalue) {
        this.changedvalue = changedvalue;
    }
    public String getChangedfrom() {
        return this.changedfrom;
    }
    
    public void setChangedfrom(String changedfrom) {
        this.changedfrom = changedfrom;
    }
    public Date getChangeddate() {
        return this.changeddate;
    }
    
    public void setChangeddate(Date changeddate) {
        this.changeddate = changeddate;
    }




}


