package ebiNeutrinoSDK.model.hibernate;
// Generated 23-gen-2012 12.30.18 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Ebiuser generated by hbm2java
 */
public class Ebiuser  implements java.io.Serializable {


     private Integer id;
     private String createdfrom;
     private Date createddate;
     private String changedfrom;
     private Date changeddate;
     private String ebiuser;
     private String passwd;
     private Boolean isAdmin;
     private String moduleid;
     private Boolean cansave;
     private Boolean canprint;
     private Boolean candelete;

    public Ebiuser() {
    }

    public Ebiuser(String createdfrom, Date createddate, String changedfrom, Date changeddate, String ebiuser, String passwd, Boolean isAdmin, String moduleid, Boolean cansave, Boolean canprint, Boolean candelete) {
       this.createdfrom = createdfrom;
       this.createddate = createddate;
       this.changedfrom = changedfrom;
       this.changeddate = changeddate;
       this.ebiuser = ebiuser;
       this.passwd = passwd;
       this.isAdmin = isAdmin;
       this.moduleid = moduleid;
       this.cansave = cansave;
       this.canprint = canprint;
       this.candelete = candelete;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCreatedfrom() {
        return this.createdfrom;
    }
    
    public void setCreatedfrom(String createdfrom) {
        this.createdfrom = createdfrom;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getChangedfrom() {
        return this.changedfrom;
    }
    
    public void setChangedfrom(String changedfrom) {
        this.changedfrom = changedfrom;
    }
    public Date getChangeddate() {
        return this.changeddate;
    }
    
    public void setChangeddate(Date changeddate) {
        this.changeddate = changeddate;
    }
    public String getEbiuser() {
        return this.ebiuser;
    }
    
    public void setEbiuser(String ebiuser) {
        this.ebiuser = ebiuser;
    }
    public String getPasswd() {
        return this.passwd;
    }
    
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }
    public Boolean getIsAdmin() {
        return this.isAdmin;
    }
    
    public void setIsAdmin(Boolean isAdmin) {
        this.isAdmin = isAdmin;
    }
    public String getModuleid() {
        return this.moduleid;
    }
    
    public void setModuleid(String moduleid) {
        this.moduleid = moduleid;
    }
    public Boolean getCansave() {
        return this.cansave;
    }
    
    public void setCansave(Boolean cansave) {
        this.cansave = cansave;
    }
    public Boolean getCanprint() {
        return this.canprint;
    }
    
    public void setCanprint(Boolean canprint) {
        this.canprint = canprint;
    }
    public Boolean getCandelete() {
        return this.candelete;
    }
    
    public void setCandelete(Boolean candelete) {
        this.candelete = candelete;
    }




}


