package ebiNeutrinoSDK.model.hibernate;
// Generated 23-gen-2012 12.30.18 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * MailTemplate generated by hbm2java
 */
public class MailTemplate  implements java.io.Serializable {


     private Integer id;
     private String setfrom;
     private Date setdate;
     private String name;
     private String template;
     private Boolean isactive;

    public MailTemplate() {
    }

    public MailTemplate(String setfrom, Date setdate, String name, String template, Boolean isactive) {
       this.setfrom = setfrom;
       this.setdate = setdate;
       this.name = name;
       this.template = template;
       this.isactive = isactive;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getSetfrom() {
        return this.setfrom;
    }
    
    public void setSetfrom(String setfrom) {
        this.setfrom = setfrom;
    }
    public Date getSetdate() {
        return this.setdate;
    }
    
    public void setSetdate(Date setdate) {
        this.setdate = setdate;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getTemplate() {
        return this.template;
    }
    
    public void setTemplate(String template) {
        this.template = template;
    }
    public Boolean getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(Boolean isactive) {
        this.isactive = isactive;
    }




}


