package ebiNeutrinoSDK.model.hibernate;
// Generated 23-gen-2012 12.30.18 by Hibernate Tools 3.4.0.CR1



/**
 * MailAttach generated by hbm2java
 */
public class MailAttach  implements java.io.Serializable {


     private Integer id;
     private String mailAttachid;
     private String filename;
     private byte[] filebin;

    public MailAttach() {
    }

    public MailAttach(String mailAttachid, String filename, byte[] filebin) {
       this.mailAttachid = mailAttachid;
       this.filename = filename;
       this.filebin = filebin;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMailAttachid() {
        return this.mailAttachid;
    }
    
    public void setMailAttachid(String mailAttachid) {
        this.mailAttachid = mailAttachid;
    }
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }
    public byte[] getFilebin() {
        return this.filebin;
    }
    
    public void setFilebin(byte[] filebin) {
        this.filebin = filebin;
    }




}


