package ebiNeutrinoSDK.model.hibernate;
// Generated 23-gen-2012 12.30.18 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * MailAssigned generated by hbm2java
 */
public class MailAssigned  implements java.io.Serializable {


     private Integer id;
     private Company company;
     private Date mailDate;
     private String setfrom;
     private String mailFrom;
     private String mailTo;
     private String mailCc;
     private String mailSubject;
     private String mailMessage;
     private String attachid;

    public MailAssigned() {
    }

    public MailAssigned(Company company, Date mailDate, String setfrom, String mailFrom, String mailTo, String mailCc, String mailSubject, String mailMessage, String attachid) {
       this.company = company;
       this.mailDate = mailDate;
       this.setfrom = setfrom;
       this.mailFrom = mailFrom;
       this.mailTo = mailTo;
       this.mailCc = mailCc;
       this.mailSubject = mailSubject;
       this.mailMessage = mailMessage;
       this.attachid = attachid;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    public Date getMailDate() {
        return this.mailDate;
    }
    
    public void setMailDate(Date mailDate) {
        this.mailDate = mailDate;
    }
    public String getSetfrom() {
        return this.setfrom;
    }
    
    public void setSetfrom(String setfrom) {
        this.setfrom = setfrom;
    }
    public String getMailFrom() {
        return this.mailFrom;
    }
    
    public void setMailFrom(String mailFrom) {
        this.mailFrom = mailFrom;
    }
    public String getMailTo() {
        return this.mailTo;
    }
    
    public void setMailTo(String mailTo) {
        this.mailTo = mailTo;
    }
    public String getMailCc() {
        return this.mailCc;
    }
    
    public void setMailCc(String mailCc) {
        this.mailCc = mailCc;
    }
    public String getMailSubject() {
        return this.mailSubject;
    }
    
    public void setMailSubject(String mailSubject) {
        this.mailSubject = mailSubject;
    }
    public String getMailMessage() {
        return this.mailMessage;
    }
    
    public void setMailMessage(String mailMessage) {
        this.mailMessage = mailMessage;
    }
    public String getAttachid() {
        return this.attachid;
    }
    
    public void setAttachid(String attachid) {
        this.attachid = attachid;
    }




}


