package ebiNeutrinoSDK.model.hibernate;
// Generated 23-gen-2012 12.30.18 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * SetReportparameter generated by hbm2java
 */
public class SetReportparameter  implements java.io.Serializable {


     private Integer paramid;
     private SetReportformodule setReportformodule;
     private Integer position;
     private Date createddate;
     private String createdfrom;
     private String paramname;
     private String paramtype;

    public SetReportparameter() {
    }

    public SetReportparameter(SetReportformodule setReportformodule, Integer position, Date createddate, String createdfrom, String paramname, String paramtype) {
       this.setReportformodule = setReportformodule;
       this.position = position;
       this.createddate = createddate;
       this.createdfrom = createdfrom;
       this.paramname = paramname;
       this.paramtype = paramtype;
    }
   
    public Integer getParamid() {
        return this.paramid;
    }
    
    public void setParamid(Integer paramid) {
        this.paramid = paramid;
    }
    public SetReportformodule getSetReportformodule() {
        return this.setReportformodule;
    }
    
    public void setSetReportformodule(SetReportformodule setReportformodule) {
        this.setReportformodule = setReportformodule;
    }
    public Integer getPosition() {
        return this.position;
    }
    
    public void setPosition(Integer position) {
        this.position = position;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getCreatedfrom() {
        return this.createdfrom;
    }
    
    public void setCreatedfrom(String createdfrom) {
        this.createdfrom = createdfrom;
    }
    public String getParamname() {
        return this.paramname;
    }
    
    public void setParamname(String paramname) {
        this.paramname = paramname;
    }
    public String getParamtype() {
        return this.paramtype;
    }
    
    public void setParamtype(String paramtype) {
        this.paramtype = paramtype;
    }




}


